server:
  port: 8080
  maxHttpHeaderSize: 10240000
  tomcat:
    max-http-post-size: -1
spring:
  datasource:
    url: jdbc:mysql://123.57.185.1:3306/nivi?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      auto-commit: true
      idle-timeout: 600000 #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      pool-name: DatebookHikariCP
      max-lifetime: 600000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      connection-timeout: 600000
      connection-test-query: SELECT 1
      login-timeout: 5
      validation-timeout: 3000
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 100 #资源池允许最大空闲的连接数 默认值8 建议值
        min-idle: 1 #资源池确保最少空闲的连接数 默认值0 建议值
        max-active: 1000 #最大连接数,设 0 为没有限制
        max-wait: -1 #jedis池没有对象返回时，最大等待时间 最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
#    password: cny121@ic
mybatis:
  mapper-locations: classpath:mappings/modules/**/*.xml